/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithNavbarRouteImport } from './routes/_with-navbar'
import { Route as WithNavbarIndexRouteImport } from './routes/_with-navbar/index'

const WithNavbarRoute = WithNavbarRouteImport.update({
  id: '/_with-navbar',
  getParentRoute: () => rootRouteImport,
} as any)
const WithNavbarIndexRoute = WithNavbarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WithNavbarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof WithNavbarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof WithNavbarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_with-navbar': typeof WithNavbarRouteWithChildren
  '/_with-navbar/': typeof WithNavbarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/_with-navbar' | '/_with-navbar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WithNavbarRoute: typeof WithNavbarRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_with-navbar': {
      id: '/_with-navbar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WithNavbarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_with-navbar/': {
      id: '/_with-navbar/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WithNavbarIndexRouteImport
      parentRoute: typeof WithNavbarRoute
    }
  }
}

interface WithNavbarRouteChildren {
  WithNavbarIndexRoute: typeof WithNavbarIndexRoute
}

const WithNavbarRouteChildren: WithNavbarRouteChildren = {
  WithNavbarIndexRoute: WithNavbarIndexRoute,
}

const WithNavbarRouteWithChildren = WithNavbarRoute._addFileChildren(
  WithNavbarRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WithNavbarRoute: WithNavbarRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
